# Ubuntu 18.04 Trusty support
sudo: required
dist: bionic

# Only build test master & travis
branches:
  only:
  - master
  - travis

# Enable C++ support
language: cpp

# Need MYCC and MYCXX as travis overwrites CC and CXX

before_install:
  - sudo apt-get -y install ${MYPACKAGES}

env:
  - MYCC=gcc-5 MYCXX=g++-5 MYPACKAGES="g++-5 python3-dev"
  - MYCC=gcc-6 MYCXX=g++-6 MYPACKAGES="g++-6 python3-dev"
  - MYCC=gcc-7 MYCXX=g++-7 MYPACKAGES="g++-7 python3-dev"
  - MYCC=gcc-8 MYCXX=g++-8 MYPACKAGES="g++-8 python3-dev"
  - MYCC=clang-3.9 MYCXX=clang++-3.9 MYPACKAGES="clang-3.9 python3-dev"
  - MYCC=clang-4.0 MYCXX=clang++-4.0 MYPACKAGES="clang-4.0 python3-dev"
  - MYCC=clang-5.0 MYCXX=clang++-5.0 MYPACKAGES="clang-5.0 python3-dev"
  - MYCC=clang-6.0 MYCXX=clang++-6.0 MYPACKAGES="clang-6.0 python3-dev"
  - MYCC=clang-7 MYCXX=clang++-7 MYPACKAGES="clang-7 python3-dev"
  - MYCC=clang-8 MYCXX=clang++-8 MYPACKAGES="clang-8 python3-dev"

arch:
  - amd64
  - arm64

# clang-5 for arm64 is missing
jobs:
  exclude:
    - arch: arm64
      env: MYCC=clang-5.0 MYCXX=clang++-5.0 MYPACKAGES="clang-5.0 python3-dev"

# Build steps
script:
  - mkdir build
  - cd build
  - CC=$MYCC CXX=$MYCXX cmake -DTREAT_WARNINGS_AS_ERRORS=1 .. && make VERBOSE=1
  - ctest --output-on-failure

notifications:
  email:
    - tomi.valkeinen@iki.fi
